
module Verification.Impure.Program.MetaBuilder.Configuration.Project where

open import Verification.Conventions
open import Verification.Impure.Builtin
open import Verification.Impure.Reflection.Definition

-- data HaskellStackProjectConfig = HaskellStackProjectConfig
--   { haskellStackBin_RelFile   :: FilePath
--   , haskellStackSource_RelDir :: FilePath
--   , haskellStackDependencySibling_RelDirs :: [FilePath]
--   , haskellStackAutobuild     :: Bool
--   , installGlobal             :: Bool
--   }
--   deriving (Generic, Show)
-- instance FromJSON HaskellStackProjectConfig



record RustProjectConfig : 𝒰₀ where
  field
    rustSource-RelDir : FilePath
    rustBin-Name : FilePath


_ = #generate-haskell RustProjectConfig


---------------------------------------------------------------
---------- v v v v     Generated by HATA     v v v v ----------
----------
----------   everything below is auto generated    ------------
---------------------------------------------------------------



